[package]
name = "memory_admin_simulator"
version = "0.1.0"
authors = ["MarioJim <mario.emilio.j@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
